# Generated by Django 5.0.2 on 2024-02-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField(unique=True)),
                ('set_title', models.CharField(max_length=100)),
                ('set_slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(unique=True)),
                ('word_ukrainian', models.CharField(max_length=100)),
                ('word_english', models.CharField(max_length=100)),
                ('word_roman', models.CharField(max_length=100)),
                ('word_pronounciation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocab.word_sets')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vocab.words')),
            ],
        ),
    ]
