# Generated by Django 5.0.2 on 2024-02-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set_Word',
            new_name='Set_Word_Junction',
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
        migrations.RenameModel(
            old_name='Word_Sets',
            new_name='Word_Set',
        ),
    ]
