# Generated by Django 5.0.2 on 2024-02-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_rename_set_word_set_word_junction_rename_words_word_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set_word_junction',
            options={'ordering': ['word']},
        ),
        migrations.AddField(
            model_name='word_set',
            name='set_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
