# Generated by Django 5.0.2 on 2024-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_alter_set_word_junction_options_word_set_set_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_examples',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_explanation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_pronounciation_audio',
            field=models.URLField(null=True),
        ),
    ]
