# Generated by Django 5.0.2 on 2024-03-01 20:48

import django.contrib.postgres.fields
import vocab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_alter_word_word_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_english',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=vocab.models.default_english_words, size=None),
        ),
    ]
