# Generated by Django 5.0.2 on 2024-03-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_alter_word_word_english'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set_Word_Junction',
            new_name='WORD_SET_JUNCTION_UKR_ENG',
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='WORD_UKR_ENG',
        ),
    ]
