# Generated by Django 5.0.2 on 2024-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_rename_set_word_junction_word_set_junction_ukr_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_ukr_eng',
            name='word_english',
            field=models.CharField(max_length=100),
        ),
    ]
