# Generated by Django 5.0.2 on 2024-03-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_alter_word_ukr_eng_word_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_set_junction_ukr_eng',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word_ukr_eng'),
        ),
    ]
