# Generated by Django 5.0.2 on 2024-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0011_alter_word_set_junction_ukr_eng_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_ukr_eng',
            name='word_definition',
            field=models.TextField(null=True),
        ),
    ]
