# Generated by Django 5.0.2 on 2024-04-03 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0015_rename_word_set_scores_set_ukr_eng_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set_ukr_eng_scores',
            options={'verbose_name': 'Set Score (UKR/ENG)', 'verbose_name_plural': 'Set Scores (UKR/ENG)'},
        ),
        migrations.AlterModelOptions(
            name='word_set',
            options={'verbose_name': 'Set (UKR/ENG)', 'verbose_name_plural': 'Sets (UKR/ENG)'},
        ),
        migrations.AlterModelOptions(
            name='word_set_junction_ukr_eng',
            options={'ordering': ['word'], 'verbose_name': 'Word/Set Junction(UKR/ENG)', 'verbose_name_plural': 'Word/Set Junctions (UKR/ENG)'},
        ),
        migrations.AlterModelOptions(
            name='word_ukr_eng',
            options={'verbose_name': 'Word (UKR/ENG)', 'verbose_name_plural': 'Words (UKR/ENG)'},
        ),
        migrations.AlterModelOptions(
            name='word_ukr_eng_scores',
            options={'verbose_name': 'Word Score (UKR/ENG)', 'verbose_name_plural': 'Word Scores (UKR/ENG)'},
        ),
        migrations.AlterField(
            model_name='word_ukr_eng',
            name='word_part_of_speech',
            field=models.IntegerField(choices=[(0, 'Noun'), (1, 'Verb'), (2, 'Adjective'), (3, 'Adverb'), (4, 'Pronoun'), (5, 'Numeral'), (6, 'Preposition'), (7, 'Conjunction'), (8, 'Interjection'), (9, 'Particle')], default=0),
        ),
        migrations.CreateModel(
            name='USER_UKR_ENG_META',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_flashcards_longest', models.IntegerField(default=0)),
                ('streak_flashcards_current', models.IntegerField(default=0)),
                ('streak_spelling_longest', models.IntegerField(default=0)),
                ('streak_spelling_current', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Meta',
                'verbose_name_plural': 'User Meta Data',
            },
        ),
        migrations.CreateModel(
            name='USER_UKR_ENG_TEST_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Test Log Record',
                'verbose_name_plural': 'User Test Log Records',
            },
        ),
    ]
