# Generated by Django 5.0.2 on 2024-04-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0017_user_ukr_eng_test_log_quiz_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ukr_eng_test_log',
            name='user_meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ukr_eng_meta', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
