# Generated by Django 5.0.2 on 2024-04-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0019_alter_user_ukr_eng_test_log_user_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_ukr_eng_test_log',
            name='user_meta',
        ),
    ]
