# Generated by Django 5.0.2 on 2024-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0021_user_ukr_eng_test_log_user_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ukr_eng_meta',
            name='tour_message_home_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_ukr_eng_meta',
            name='tour_message_word_details_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_ukr_eng_meta',
            name='tour_message_word_list_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_ukr_eng_meta',
            name='tour_message_word_sets_one',
            field=models.BooleanField(default=True),
        ),
    ]
