# Generated by Django 5.0.2 on 2024-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0023_user_ukr_eng_meta_tour_message_quiz_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALPHABET_UKR_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.IntegerField(unique=True)),
                ('letter_ukrainian', models.CharField(max_length=100)),
                ('letter_explanation', models.CharField(max_length=100)),
                ('letter_pronounciation_audio', models.URLField(null=True)),
                ('letter_examples', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Letter (UKR/ENG)',
                'verbose_name_plural': 'Alphabet (UKR/ENG)',
            },
        ),
    ]
