# Generated by Django 5.0.2 on 2024-04-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0024_alphabet_ukr_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ukr_eng_meta',
            name='tour_message_alphabet_one',
            field=models.BooleanField(default=True),
        ),
    ]
