name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd /var/www/vocabventure/VocabVenture
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vocabventure/VocabVenture
            git pull
            source venv/bin/activate
            ./manage.py migrate
            ./manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
